basePath: /api/v1
definitions:
  Event.Event:
    properties:
      description:
        type: string
      endDate:
        type: string
      id:
        type: string
      name:
        type: string
      startDate:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@example.com
    name: API Support
    url: http://example.com/support
  description: This is a sample Gin server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://example.com/terms/
  title: My App API
  version: "1.0"
paths:
  /events:
    get:
      consumes:
      - application/json
      parameters:
      - description: Filter events by date
        enum:
        - past
        - present
        - future
        in: query
        name: filter
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/Event.Event'
            type: array
      summary: Get Events
      tags:
      - Events
schemes:
- http
swagger: "2.0"
